version: 0.0
os: linux
files:
   - source: /data
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
